[package]
name = "exam"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
serde = "1.0.218"
serde_json = "1.0.139"
ureq = "3.0.7"

simeis-data = { path = "../simeis/simeis-data" }
crossterm = "0.28.1"
color-eyre = "0.6.3"
